# Generated by Django 2.1.7 on 2019-02-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Vmv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=20)),
                ('engine_cc', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('seating_capacity', models.IntegerField()),
                ('v_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Model')),
            ],
        ),
    ]
