# Generated by Django 2.1.7 on 2019-02-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand_model_vmv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='CarModel',
        ),
    ]
