# Generated by Django 2.1.7 on 2019-02-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
